"""creating appointment table

Revision ID: 45ed8e7cf125
Revises: 9c5b4b112f4d
Create Date: 2026-02-06 13:51:28.527701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ed8e7cf125'
down_revision: Union[str, Sequence[str], None] = '9c5b4b112f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('patient_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'patient_name')
    # ### end Alembic commands ###
