"""creating appointment table

Revision ID: a822c1fb72fa
Revises: 45ed8e7cf125
Create Date: 2026-02-06 14:08:41.587847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a822c1fb72fa'
down_revision: Union[str, Sequence[str], None] = '45ed8e7cf125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'patient_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'patient_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
