"""creating appointment table

Revision ID: ce9f9670e570
Revises: 51ac5bf4eedd
Create Date: 2026-02-06 14:31:16.473711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9f9670e570'
down_revision: Union[str, Sequence[str], None] = '51ac5bf4eedd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('user_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'user_name')
    # ### end Alembic commands ###
